# Generated by Django 5.1.4 on 2025-01-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='types',
            field=models.ManyToManyField(related_name='foods', to='foods.food_type'),
        ),
    ]
