# Generated by Django 5.1.4 on 2025-01-09 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_food_types2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='types',
        ),
    ]
