# Generated by Django 5.1.4 on 2025-01-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_remove_food_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='types2',
            new_name='types',
        ),
    ]
