# Generated by Django 5.1.4 on 2025-01-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_rename_types2_food_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='types',
            new_name='typesOfFood',
        ),
    ]
