# Generated by Django 5.1.4 on 2025-01-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0007_rename_types_food_typesoffood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_type',
            new_name='Food_type2',
        ),
    ]
