# Generated by Django 5.1.4 on 2025-01-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_rename_food_type_food_type2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_type3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Food_type2',
        ),
    ]
