# Generated by Django 5.1.4 on 2025-01-09 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0009_food_type3_delete_food_type2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_type3',
            new_name='Food_type2',
        ),
    ]
