# Generated by Django 5.1.4 on 2025-01-10 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_rename_food_type3_food_type2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food_type2',
        ),
    ]
