# Generated by Django 5.1.4 on 2025-01-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
